---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
    autoupdate_commit_msg: 'chore: update pre-commit hooks'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace

-   repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
    -   id: yamlfmt
        args: [--mapping, '4', --sequence, '4', --offset, '0']

-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.15.0
    hooks:
    -   id: pretty-format-toml
        args: [--autofix, --indent, '4']

-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    -   id: codespell
        args: [--toml=pyproject.toml]
        additional_dependencies: [tomli]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
    -   id: mypy
        additional_dependencies: [pandas-stubs, types-requests]
        args: [--config-file=pyproject.toml]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
    # Run the linter.
    -   id: ruff
        # args: [--statistics]
        args: [--fix, --show-fixes]
    # Run the formatter.
    -   id: ruff-format
