# file generated by setuptools_scm
# don't change, don't track in version control
from __future__ import annotations

__version__ = version = "0.2.1.dev40+g304daf4.d20230908"
__version_tuple__ = version_tuple = (0, 2, 1, "dev40", "g304daf4.d20230908")
